### ISSUE TITLE
License?  Package?  Alternatives?

### ISSUE THREAD

**Issue by alphapapa** [VincentToups/destructuring-set#1]
Hi there,

Having (re)stumbled upon some of your GitHub projects, I came across this, and I immediately thought of some places I could use it in a recent elisp project of mine.  I realize that it's been a while since you've touched this, so I was wondering about using it in my project.

1.  Is there an alternative I should use instead?  I've seen your shadchen-el, but I haven't grokked it yet.  Should I look into that instead?
2.  If this is still useful on its own, would you consider packaging it for MELPA?
3.  Otherwise, would you add a license so I could use it in my project?

Hm, I feel like I should have written those questions as a `cond` or `pcase`.  :)

Thanks!

**Comment by VincentToups** [comment]
Shadchen-el is definitely where you want to go with this kind of thing and its already on elpa and melpa. But if you specifically want to destructure and side effect in one go, feel free to treat this code as being in the public domain.

Is your username a reference to Alan Partridge, by any chance?

**Comment by alphapapa** [comment]
Ok, thanks.  So IIUC, shadchen is generally a better solution, but `destructuring-set` is what would work in a `cl-loop`, right?  `cl-loop`'s own destructuring works well, but only in a `for` assignment; in a `do (setq ...` it doesn't help.

My username is just my initials in the phonetic alphabet, but I looked up that name on Wikipedia, so I guess I'll have to look up some of his funny videos now.  :)

**Comment by VincentToups** [comment]
It really depends on what you are trying to do. Can you give me more context?

**Comment by alphapapa** [comment]
Well, sure.  This code is pretty ugly, and not necessarily where I'd use it, but this is the kind of place I was thinking about using `destructuring-set`: https://github.com/alphapapa/org-super-agenda/blob/master/org-super-agenda.el#L595

**Comment by VincentToups** [comment]
Ha - that is some serious cl-loop work. I tend towards functional approaches, so I'd probably dispense with all the loop machinery in factor of a `reduce` over `org-super-agenda-groups` and then I'd define some pattern matching functions using shadchen's function definition forms. Or, if I wanted to put it all in one place, I'd use `match` or `match-let`. In the former case, I'd write one function body for each possible case in the loop and construct the result iteratively. Finally, I'd apply the transformations in the finally clause, probably as a function call of a locally defined function using `flet`. 

All this is a matter of taste, but I almost never `setq` in code I write. In this case it doesn't seem like you need to side effect for performance or memory reasons, so I'd refactor the code to be completely pure.

**Comment by alphapapa** [comment]
Thanks, I appreciate your taking the time to look at that spaghetti and give feedback.  :)  Recursive and purely functional code is still a bit over my head, but I'm trying to move in that direction.  Good tools and examples like yours help.

By the way, I happened upon your clocks page--extremely impressive!  Some of them are just mesmerizing.  I wish I could write stuff like that, but I don't have the math background.  I was thinking, if I were CEO of some company, I'd put up a big screen in the lobby with your clocks on it!  Well, I'd do it at home, too, if I had a suitable setup.  :)

**Comment by VincentToups** [comment]
People should program in whatever way they are comfortable. Its certainly possible (indeed, I've done it) to create terrifying messes in any style. 

That said, functional programming, for me, is so enormously useful. I find it helps me write correct code very quickly, with less mess. I strongly recommend it. 

A good place to start is by learning Scheme, probably with Structure and Interpretation of Computer Programs. Scheme is a dialect which really encourages functional style even though it isn't entirely pure. Its  a great way to ease into the practice. 

Thanks for the comments about Clocks! I don't have time to pursue all my interests these days, but its nice when someone says something nice about them!

**Comment by alphapapa** [comment]
Thanks for the pointers.  Reading the classic books like SICP, the Schemer books, etc. are on my list of great literature to get around to someday...  In the meantime I take shortcuts by studying things like your software and groping around in the dark.  ;)
